### ISSUE TITLE
Modo aventura

### ISSUE THREAD

**Issue by MacacoLunar** [john-titor-master/bombcrypto-superbot#1]
Modo aventura está sempre jogando com o mesmo hero, acho que isso pode dar ban.

**Comment by john-titor-master** [comment]
Sim. Isso foi intencional. O servidor do jogo não bloqueia o uso do mesmo herói para jogar o modo aventura. Utilizei esta estratégia de forma a maximizar meu ganho (herói mais raro gera mais BCOINS). Você pode abrir um Pull Request fazendo rotação de heróis e até respeitando o tempo limite do uso dos heróis, ou simplesmente comentar a função do modo aventura.
