### ISSUE TITLE
Bug function 'There are no heroes to work now'

### ISSUE THREAD

**Issue by ghost** [john-titor-master/bombcrypto-superbot#12]
Bom dia.

Mesmo com a opção ADVENTURE=0 ou sem setar essa variavel no start, o bot está chamando a função para jogar o modo aventura, quando não há herois para trabalhar (l:360 src/bot.ts)

E também, na inicialização do bot, se você setar a variavel ADVENTURE= independente do valor que setar (0 ou 1) o modo aventura estara ativo e esta usando as chaves.

![BUG](https://user-images.githubusercontent.com/39542354/158063079-07e8d97e-dbb1-4c44-a074-44fcd10aaecc.png)

**Comment by john-titor-master** [comment]
Corrigido.
