### ISSUE TITLE
request> more telegram functions

### ISSUE THREAD

**Issue by xclover0** [john-titor-master/bombcrypto-superbot#13]
hello. would it be possible to add more telegram functions? like showing the following:
invested bcoin, total mined, ROI %, and reward %?

![zz](https://user-images.githubusercontent.com/97353862/158068386-4510d7d0-1550-4be7-94c5-21538adb9265.jpg)

**Comment by Mozez20** [comment]
Hi @john-titor-master 

How can I add the variable walletId to the messages?

```
            const message =
                `Wallet Id: ${???}\n` +
                `Working heroes: ${this.workingSelection.length}\n` +
                `Map: ${this.map.toString()}\n` +
                `IDX: ${this.index}`;
```

Good job, thanks!

**Comment by waelsy123** [comment]
I think you can get that from the blockchain blocks data https://bscscan.com/tx/0xde63d5d2fadeb7280dff20161a8fccbac9f376d554f8df7cca33fb002490db2a

**Comment by john-titor-master** [comment]
Included on `/rewards` command.
