### ISSUE TITLE
More than 15 heroes 

### ISSUE THREAD

**Issue by waelsy123** [john-titor-master/bombcrypto-superbot#18]
I have noticed two issues here: 

1. Squad:: get heroes() return only the active heroes which is MAX 15 hero. is there a way to get the full list of heroes (including the inactive ones)? 
2. Is it possible to rotate active heroes in case we have more than 15 heroes in an account?

**Comment by rastogiujj12** [comment]
disabled heroes do not regenerate stamina, so there's no use for rotating heroes.

**Comment by john-titor-master** [comment]
Se quiser explicar um pouco melhor o porquê de rotacionar heróis desativados hehe.
