### ISSUE TITLE
erro a partir de 21/03, ajuda =)

### ISSUE THREAD

**Issue by alegalati123** [john-titor-master/bombcrypto-superbot#19]
![yarn go](https://user-images.githubusercontent.com/96633555/159267619-9abad955-1f04-4289-b0b4-f329cef88b78.png)
comecei a ter esse erro hoje.

alguém pode me ajudar? Obrigado!!

**Comment by john-titor-master** [comment]
Só atualizar a sua versão :)

**Comment by alegalati123** [comment]
Maravilha, agora foi! obrigado!
