### ISSUE TITLE
Constants

### ISSUE THREAD

**Issue by MacacoLunar** [john-titor-master/bombcrypto-superbot#2]
Vi que tem um arquivo com algumas constantes, tais como:
SALT_KEY, DATE_OFFSET, VERSION_CODE

Como saber os novos valores após uma atualização?

**Comment by john-titor-master** [comment]
`DATE_OFFSET` é sempre o mesmo valor independente de atualizações. O jogo utilizada números do tipo `LONG` para armazenar datas. É parecido com `Date.now()`, mas ao invés de ser desde `1970-01-01T00:00:00.000Z`, é desde `0001-01-01T00:00:00.000Z`.

`VERSION_CODE` está sempre presente na tela inicial do jogo.

`SALT_KEY` essa é a chave de criptografia que o jogo usa para validar as mensagens. Ela muda raramente entre atualizações. Quando isso acontece, é necessário escanear a memória do jogo buscando o novo valor.
