### ISSUE TITLE
How to use 

### ISSUE THREAD

**Issue by tholakk** [john-titor-master/bombcrypto-superbot#20]
can you help me used this tool easily.

i don't know how to do. 

telegram : @thotq

**Comment by Mozez20** [comment]
Follow the README > Installation
https://github.com/john-titor-master/bombcrypto-superbot#installation

Have you found any problem?

**Comment by tholakk** [comment]
yes, i have problem when installation and don't know how to turn on this tool. 
I installed all of these: https://git-scm.com/downloads
https://nodejs.org/en/download/ Version 16 at least.

And  installed all of these:
npm install -g yarn
git clone https://github.com/john-titor-master/bombcrypto-superbot
cd bombcrypto-superbot
yarn install .

But i don't know what to do next?

Can you inbox for me and i will sent image and help me. please

**Comment by Mozez20** [comment]
WALLET_ID=wallet_id yarn go
Replace wallet_id with your wallet id.

**Comment by tholakk** [comment]
> WALLET_ID=wallet_id yarn go Replace wallet_id with your wallet id.

how to use for multi account bro?

**Comment by ghost** [comment]
> > WALLET_ID=wallet_id yarn go Replace wallet_id with your wallet id.
> 
> how to use for multi account bro?

Open as many terminals as you need. 1 terminal for each account. each terminal do you need to set the wallet_id.

**Comment by tholakk** [comment]
no bro, when i open 2 terminals to run this Git Bash. It error. And just running Git Bash 2 . Git bash 1 error and  don't running. 

This is error :

TelegramError: 409: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
    at Telegram.callApi (C:\Users\quang\OneDrive\Desktop\Raca\bombcrypto-superbot\node_modules\telegraf\lib\core\network\client.js:263:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Polling.[Symbol.asyncIterator] (C:\Users\quang\OneDrive\Desktop\Raca\bombcrypto-superbot\node_modules\telegraf\lib\core\network\polling.js:27:33)
    at async Polling.loop (C:\Users\quang\OneDrive\Desktop\Raca\bombcrypto-superbot\node_modules\telegraf\lib\core\network\polling.js:69:30) {
  response: {
    ok: false,
    error_code: 409,
    description: 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'
  },
  on: {
    method: 'getUpdates',
    payload: { timeout: 50, offset: 0, allowed_updates: [] }

**Comment by john-titor-master** [comment]
From the multi-account section:

> For each bot, you need a *different* telegram key to communicate with them.

**Comment by tholakk** [comment]
thanks bro for supported me for a lot. i made it and very happy about this tool 👯 

hope you always update tool if game update  🗡️
