### ISSUE TITLE
Telegram bots

### ISSUE THREAD

**Issue by Mozez20** [john-titor-master/bombcrypto-superbot#21]
So far I have created a bot for each account, but it's somewhat cumbersome and I think that Telegram has some limit on the maximum number of bots (already found... Sorry, too many attempts. Please try again in 60915 seconds.)

Is it possible to use a single bot for all accounts?

**Comment by john-titor-master** [comment]
It is not currently implemented on the bot, but it might be possible. The bots would need to send such data to some centralized store and the telegram bot would fetch it from each of the bots. If you implement it, feel free to open a PR.

**Comment by Mozez20** [comment]
I thought it could be done in some simple way.
The idea of a single bot would be great, but it's beyond my limited knowledge of the language.

I think I will implement something basic, such as sending balances using Discord webhooks on each login (nothing fancy or that could contribute much to the project unfortunately).

Thanks for answering!
