### ISSUE TITLE
hero not counting correctly (working/resting)

### ISSUE THREAD

**Issue by xclover0** [john-titor-master/bombcrypto-superbot#23]
![notes](https://user-images.githubusercontent.com/97353862/160281598-c9c7b64f-1d96-4c81-97cb-1cd2092e1d9c.jpg)

I have 15 heroes on account, only 14 is at rest and 0 (zero) on work. it should be 15 in total..

**Comment by lucasvieceli** [comment]
done test here,

Is he not inactive?
![Captura de Tela 2022-03-28 às 10 35 09](https://user-images.githubusercontent.com/1795678/160409941-f760e4b8-5caa-4648-b684-9109757d5db4.png)

**Comment by xclover0** [comment]
> done test here,
> 
> Is he not inactive? ![Captura de Tela 2022-03-28 às 10 35 09](https://user-images.githubusercontent.com/1795678/160409941-f760e4b8-5caa-4648-b684-9109757d5db4.png)

hey man, your PR fixed the issue. thanks
