### ISSUE TITLE
travando em login telegraf

### ISSUE THREAD

**Issue by Manowgu** [john-titor-master/bombcrypto-superbot#25]
![image](https://user-images.githubusercontent.com/101955698/160419221-87279da1-66a4-403f-9e69-f393aee77e98.png) boa tarde, meu bot esta travando nessa linha, hora passa, hora nao passa

**Comment by ghost** [comment]
É problema de conexão. Há relatos que o Server do jogo está instável. Não é problema com o bot. Verifique o discord do bombcrypto

Obs:poste imagens legíveis.

**Comment by Manowgu** [comment]
obrigado e desculpa pela foto
