### ISSUE TITLE
Off-topic

### ISSUE THREAD

**Issue by MacacoLunar** [john-titor-master/bombcrypto-superbot#3]
Já tentou fazer um bot websocket para o space crypto?

**Comment by john-titor-master** [comment]
Eu fiz um bot para o bombcrypto por diversão e aprendizado. Foi um desafio legal, aprendi a trabalhar com WASM por consequência. Mas não tenho tempo para investir nisso no momento. Mas o processo pode ser bem parecido.

**Comment by MacacoLunar** [comment]
Tentei baixar o WASM e decompilar quando comecei no bomb, mas não consegui entender muita coisa do código decompilado. Também tentei visualizar as requisições pelo browser, mas estavam ofuscadas.
Não tenho experiência com nodejs, mas seu código está tão bem escrito que estou conseguindo aprender com ele, obrigado. Parabéns pelo projeto.

**Comment by ikariwill** [comment]
Vi que tinha alguns códigos de telegram. Você usou pra alguma coisa, como receber informação das suas contas?

Ta bem legal o projeto, código de qualidade, bem escrito.

**Comment by alefwmm** [comment]
Você pode passar a variável de ambiente TELEGRAM_KEY com uma chave do telegram para um bot (gerado pelo BotFather).

Você pode usar os comandos `/stats` E `/rewards` para obter estatísticas do mapa e suas recompensas respectivamente.

**Comment by john-titor-master** [comment]
Você pode passar uma variável de ambiente `TELEGRAM_KEY` para integrar um bot do telegram, obtido pelo BotFather.

Feito isso, você pode usar os comandos /stats e /rewards em uma conversa com esse bot, obtendo estatísticas atuais do mapa e suas recompensas respectivamente.

**Comment by john-titor-master** [comment]
> Vi que tinha alguns códigos de telegram. Você usou pra alguma coisa, como receber informação das suas contas?
> 
> Ta bem legal o projeto, código de qualidade, bem escrito.

@ikariwill  Abre um PR com as modificações que você está fazendo :). Estou buscando um mantenedor hehe. Por sinal, usando Docker é melhor pro bot reiniciar em caso de falhas.

**Comment by ikariwill** [comment]
Por enquanto adicionei apenas um script pra reinicializar, fiz bem as pressas pra testar se ele conseguiria aguardar a manutenção rodando e tentando reconectar começando a cada 5 min e indo até 25 min de delay entre as retentativas.

Não deu certo pq tinha que att a constante do número da versão.

Depois dou uma olhada via docker, se surgir algum progresso abro uma PR pra contribuir.

**Comment by tripparian** [comment]
Se alguém tiver algum progresso relacionado com o spacecrypto, por favor, me da um aviso ai! Estou tentando fazer algo baseado neste código original mas tenho pouca experiência.

O código funciona muito bem para o bomb, é espetacular, brabo demais

**Comment by odilklein** [comment]
@john-titor-master cadê o ID da sua wallet na descrição no README, pra você receber doações pela contribuição?

**Comment by john-titor-master** [comment]
> @john-titor-master cadê o ID da sua wallet na descrição no README, pra você receber doações pela contribuição?

Adicionado.

**Comment by vhung85** [comment]
Hi @john-titor-master , seem that the bot is not working anymore? It still running, but not sync. Could you please check. Thank you.

**Comment by ghost** [comment]
> Hi @john-titor-master , seem that the bot is not working anymore? It still running, but not sync. Could you please check. Thank you.

There is no problem with the bot. I'm using rn and its good

**Comment by nowsys** [comment]
Hi all, just curious... is it okay for me to login the bomber through webpage while running the bot?  Please advise.

**Comment by john-titor-master** [comment]
> Hi all, just curious... is it okay for me to login the bomber through webpage while running the bot? Please advise.

Nope, once you log-in through the bot, you will get disconnected from the web page.

**Comment by CodEw47** [comment]
Hi jhon you have social media? i need talk to you.

**Comment by john-titor-master** [comment]
> Hi jhon you have social media? i need talk to you.

https://t.me/john_titor_master
You may call me on Telegram.
