### ISSUE TITLE
LoginFailed

### ISSUE THREAD

**Issue by EsliAraujo** [john-titor-master/bombcrypto-superbot#30]
Bot não está logando (estava normal à alguns dias)
O login pela web (jogo normal) funciona.
![image](https://user-images.githubusercontent.com/41961751/161163901-b296b901-8af4-4ae6-8fe7-936f7fa51941.png)

**Comment by john-titor-master** [comment]
Foi lançada uma atualização no código hoje às 07h da manhã. Atualize seu código e tudo ficará normal.
