### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tholakk** [john-titor-master/bombcrypto-superbot#35]
I don't know this issues bro. Check and help me 

[warn] src\bot.ts
[warn] Code style issues found in the above file(s). Forgot to run Prettier?

**Comment by xclover0** [comment]
go to src directory then type this on cmd/terminal

npx prettier --write bot.ts

**Comment by nortonPC2** [comment]
i dont get this

go to src directory then type this on cmd/terminal

npx prettier --write bot.ts

**Comment by xclover0** [comment]
> i dont get this
> 
> go to src directory then type this on cmd/terminal
> 
> npx prettier --write bot.ts

open your terminal/cmd.. go to SRC folder of the bot, then type that.

npx prettier --write bot.ts
![s](https://user-images.githubusercontent.com/97353862/161684320-802e073b-0d39-4f83-adb1-e845ad1f9a95.jpg)

or you can skip prettier by doing this..

WALLET_ID=wallet_id TELEGRAM_KEY=telegram_key ADVENTURE=1 yarn start

**Comment by nortonPC2** [comment]
> 

thanks
