### ISSUE TITLE
Dúvida Modo Aventura

### ISSUE THREAD

**Issue by marlindo71** [john-titor-master/bombcrypto-superbot#36]
Boa tarde, pessoal.

Parabéns pelo projeto. Estou analisando pra tentar começar a usar.

No modo aventura ele escolhe o heroi com maior raridade? Ele respeita o período de bloqueio/tempo do heroi?
Se eu tiver 2 herois épicos, por exemplo, ele joga com um e depois o outro ou utiliza sempre o mesmo?

Desculpe tantas perguntas mas é porque TypeScript não é minha praia, então ainda não consigo tirar essas dúvidas só olhando o código.

Obrigado.

**Comment by xclover0** [comment]
it only use your hero with the highest rarity (doesn't select the next high rarity after..)
