### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by smultn** [john-titor-master/bombcrypto-superbot#4]
I have installed all dependencies but keep getting this error
![image](https://user-images.githubusercontent.com/56875604/156697477-928e6e86-aa62-4473-ae8a-01028ff5522e.png)

**Comment by MacacoLunar** [comment]
You didn't set your wallet, anyway the server is off now.

**Comment by john-titor-master** [comment]
Hey @smultn, you must run it on some bash terminal. Also, do not forget to set your wallet ID:

```bash
WALLET_ID=<INSERT WALLET ID HERE> yarn go
```

**Comment by smultn** [comment]
![image](https://user-images.githubusercontent.com/56875604/156821087-5d905b56-e8ba-4354-b266-5e03522d891c.png)
getting this error, what should i do?
