### ISSUE TITLE
After the last maintenance, the it show some "Login Error"

### ISSUE THREAD

**Issue by justynik** [john-titor-master/bombcrypto-superbot#40]

**Comment by lucasvieceli** [comment]
duplicad https://github.com/john-titor-master/bombcrypto-superbot/issues/39

**Comment by Manowgu** [comment]
Lucasvieceli the bot is working for u ?

**Comment by lucasvieceli** [comment]
> Lucasvieceli the bot is working for u ?

Resultados de tradução
no,

need code correction

**Comment by Manowgu** [comment]
only jonh titor save all
