### ISSUE TITLE
After the last maintenance, It show some "Login Error"

### ISSUE THREAD

**Issue by justynik** [john-titor-master/bombcrypto-superbot#41]
`/bombcrypto-superbot/build/err.js:30`
`       return new SuperBotException(type, ${type}: ${message});`
`                  ^`
`SuperBotException: LoginFailed: Error code 101`
`...`
`...`
`...`
`... {`
`      type: 'LoginFailed'`
`}`

**Comment by Manowgu** [comment]
this error is for everyone, wait patiently
