### ISSUE TITLE
algum super heroi salva a gente

### ISSUE THREAD

**Issue by Manowgu** [john-titor-master/bombcrypto-superbot#43]
visto que o dev ta de ferias, algum super heroi consegue colocar o magnifico pra rodar ?

**Comment by xclover0** [comment]
@lucasvieceli @rmmarconi @andresandri2 can you pull up the new salt_key? seems they changed that's why we can't get an authentication.

**Comment by Manowgu** [comment]
@xclover0 u have the salt_key?

**Comment by ghost** [comment]
> @lucasvieceli @rmmarconi @andresandri2 can you pull up the new salt_key? seems they changed that's why we can't get an authentication.

Sorry disappoint you.. I have not skills to do this! Maybe @ikariwill can do this

**Comment by Manowgu** [comment]
@ikariwiĺl help

**Comment by ikariwill** [comment]
> > @lucasvieceli @rmmarconi @andresandri2 can you pull up the new salt_key? seems they changed that's why we can't get an authentication.
> 
> Sorry disappoint you.. I have not skills to do this! Maybe @ikariwill can do this

Não só o salt pode ter mudado, mas também outros parâmetros que eram encriptados e validados no server ao enviar o login do client.

Se não estiver tudo igual o que o server espera na mensagem do Websocket o login não funciona.

Pra saber os valores corretos pra montar a mensagem só observando o funcionamento do jogo a fundo. Não tenho conhecimentos em dev de games, só o @john-titor-master que vai resolver essa.

Vamos aguardar, enquanto isso usem algum auto-clicker ou bot que utilizavam anteriormente. Quando ele estiver disponível ele comenta por aqui, sempre foi bem ativo.

**Comment by gohun0096** [comment]
God teach me @john-titor-master

**Comment by gohun0096** [comment]
can you help  please @john-titor-master

**Comment by Manowgu** [comment]
Hey John is resting please wait

**Comment by LeonardoFBR** [comment]
What a great job, I hope I get to know as much as he does.

**Comment by lucasvieceli** [comment]
estou criando um bot para o instagram, a onde as pessoas podem usar meu servidor pra cadastrar suas contas pra colocar pra rodar
https://t.me/bombcryptoFreeBot

<img width="432" alt="Captura de Tela 2022-04-08 às 08 48 27" src="https://user-images.githubusercontent.com/1795678/162429816-6e4d1927-b6fa-42d2-bb97-c3cc0693bd9c.png">

**Comment by LeonardoFBR** [comment]
Is the bot already working?

**Comment by lucasvieceli** [comment]
> Is the bot already working?


not yet, he won't be back until next week


even so I don't think it will fix the bot,

last update
We currently enable the system to automatically ban user accounts that use the tool to send false signals to the server (The tools do not need to open the game but still send the game signal to the server).
❗️We strongly advise users not to use these tools to avoid getting banned❗️

We have updated the new version for Android mobile devices. Please follow these steps to download the new one (you don't need to delete the old version)

**Comment by gusstta** [comment]
a idéia desse bot é muito boa, é muito leve, talvez a solução seja usar o login de escolinha com usuário e senhas, dessa forma não estaria contra as regras

**Comment by lucasvieceli** [comment]
> a idéia desse bot é muito boa, é muito leve, talvez a solução seja usar o login de escolinha com usuário e senhas, dessa forma não estaria contra as regras

mesmo assim fica contra as regras kkk

**Comment by Manowgu** [comment]
É um excelente trabalho, John fez uma obra de arte, o bomb com inveja quer acabar

**Comment by gohun0096** [comment]
When will john update date, I really want to use it.
