### ISSUE TITLE
Offtopic telegram bot free

### ISSUE THREAD

**Issue by lucasvieceli** [john-titor-master/bombcrypto-superbot#48]
.

**Comment by tholakk** [comment]
is safe?

**Comment by ikariwill** [comment]
@lucasvieceli funcionando legal, mas depois de um tempo rodando ele para de executar com o erro:

Error in account: 
Bot is not running!

Teria que ver uma forma de reiniciar caso de esse erro, que deve ser algum timeout no server do bomb.

**Comment by lucasvieceli** [comment]
ainda estou testando, veifiquei isso agora, espero q tenha corrigido

**Comment by lucasvieceli** [comment]
> is safe?

it runs the same bot from this repository.

I run all accounts on my server

**Comment by lucasvieceli** [comment]
> @lucasvieceli funcionando legal, mas depois de um tempo rodando ele para de executar com o erro:
> 
> Error in account: Bot is not running!
> 
> Teria que ver uma forma de reiniciar caso de esse erro, que deve ser algum timeout no server do bomb.

por enquanto parece que esta corrigido

**Comment by veenx67** [comment]
rapaz, você é f***

primeiro saque vou fazer uma doação

muito obrigado <3

**Comment by veenx67** [comment]
o bot parou de responder do nada, qualquer comando que eu uso ele não responde.

**Comment by lucasvieceli** [comment]
> o bot parou de responder do nada, qualquer comando que eu uso ele não responde.

as vezes ele sobrecarrega kkkk, servidor de 1gb de ram, temos um grupo, qualquer coisa manda msg la https://t.me/+tQcb45U9MwAxYWMx

**Comment by darklain** [comment]
Oi lucas, blz prazer. Lucas fiquei sabendo do seu bot qdo acessei seu git a primeira vez vi que vc ensina como instalar configurar ele para rodar, e acessei agora e vi que vc deletou, vc nao vai disponibilizar mais como instalar? obrigado pelo desenvolvimento.
