### ISSUE TITLE
Sugestões de aprimoramento do bot

### ISSUE THREAD

**Issue by shukamu95** [john-titor-master/bombcrypto-superbot#49]
Olá pessoas,

Gostaria inicialmente de parabenizar o desenvolver do bot, funciona muito bem e a integração com o telegram é filé!

Sugestão:
Problema: Heróis com mais stamina ou raridade maior demoram muito para ir trabalhar, já que o calculo é baseado em % de stamina cheia. Alterando o MIN_HERO_ENERGY para um número inferior também causaria um problema com heróis que tem stamina baixa ou bateria.

Exemplo:
Comum 25/50 energia - (energia herói / energia máxima) * 100 = 50%
Comum 25/100 energia - (energia herói / energia máxima) * 100 = 25%
Épico 25/550 energia - (energia herói / energia máxima) * 100 = 4,5%

O boneco épico iria demorar muito para ir trabalhar, porém ele é o que quebra os blocos mais rápido, já os comuns trabalhariam mais com menor eficiência, já que os heróis mais fortes também tem skills ou quebram outros blocos por consequência no processo.

Solução queeu fiz no meu, mas na gambiarra kkk:
Alterar o calculo de % para valor total da energia e setar um número mínimo para qualquer herói trabalhar

Eu alterei no arquivo bot.ts 
LINHA 28:
const MIN_HERO_ENERGY = 49;

LINHA 216: 
const percent = (hero.energy / 1) * 1;

não sei se somente (hero.energy) já funcionária na função, não manjo de programação no nível de vocês, então deixei o mesmo código e só fiz divisão e multiplicação por 1 da energia do herói para dar a energia atual.

Imagino que também seja possível melhorar a eficiência de mineração se for possível definir quais tipos de bloco tem no mapa e a vida atual deles para fazer a escolha dos heróis que vão trabalhar.

**Comment by lucasvieceli** [comment]
no pull request eu fiz uma env MIN_HERO_ENERGY_PERCENTAGE

fiz agora antes de ler seu comentário kkkk
