### ISSUE TITLE
Parou de rodar após atualização de 04/03/2022

### ISSUE THREAD

**Issue by ciborgcarom** [john-titor-master/bombcrypto-superbot#5]
@john-titor-master 

Parabéns pelo projeto e obrigado por compartilhar!! 

Gostei muito e já comecei a estudar WASM, pois nem sabia o que era.

Ontem rodei o projeto e funcionou de boa até às 23h, porém hoje após a atualização, não está funcionando. 
![image](https://user-images.githubusercontent.com/6770435/156760379-be8193be-e7e9-46b2-aade-e50729afbfa4.png)

Olhando pelo seu código e tentando entender, pode ser que eles tenham mudado a **SALT_KEY**, mas é um mero chute. Ainda não consigo entender o motivo.

**Comment by alcidesbsilvaneto** [comment]
Nunca tinha visto esse bot, no dia que vou usar, quebra kkkkkk. Que azar, aguardando correção.

**Comment by jeanvetorello** [comment]
mesma coisa, depois da atualizaçao parece que não dá para entrar só com a wallet.

que pena deixou a gente sonhar.

**Comment by john-titor-master** [comment]
Apenas mudaram a versão de 33 para 34 :stuck_out_tongue:.

**Comment by jeanvetorello** [comment]
> Apenas mudaram a versão de 33 para 34 😛.

Chef toda vez que mudar de ver temos que alterar nesse aquivo ai?
daria para colocar como env tambem?
