### ISSUE TITLE
Sugestão para implementar casa

### ISSUE THREAD

**Issue by ghost** [john-titor-master/bombcrypto-superbot#6]
Boa tarde. Seria possível implementar casa? E dar prioridade nos herois com maior raridade para ela?

**Comment by john-titor-master** [comment]
Eu não implementei a casa porque eu mesmo não tinha uma. No momento estou um pouco focado em outros projetos e não pretendo implementar essa funcionalidade, até porque precisaria de uma conta com uma casa para testar. Tenho alguns amigos capazes de implementar, mas que fariam com as devidas recompensas hehe. Se estiver interessado me avisa.

**Comment by zomanuniverse** [comment]
> I didn't implement the house because I didn't have one myself. At the moment I'm a little focused on other projects and I don't intend to implement this functionality, because I would need an account with a house to test. I have some friends able to implement it, but they would do it with the proper rewards hehe. If interested let me know.

I am amazed at your work.
I own a house if you want the address of the wallet let me know, and I need to donate to you because you are really a genius

**Comment by ghost** [comment]
> Eu não implementei a casa porque eu mesmo não tinha uma. No momento estou um pouco focado em outros projetos e não pretendo implementar essa funcionalidade, até porque precisaria de uma conta com uma casa para testar. Tenho alguns amigos capazes de implementar, mas que fariam com as devidas recompensas hehe. Se estiver interessado me avisa.


Tenho interesse.. Entra em contato comigo em hellsink@gmail.com para conversamos melhor e tirar uma dúvida, @john-titor-master

**Comment by alefwmm** [comment]
> > Eu não implementei a casa porque eu mesmo não tinha uma. No momento estou um pouco focado em outros projetos e não pretendo implementar essa funcionalidade, até porque precisaria de uma conta com uma casa para testar. Tenho alguns amigos capazes de implementar, mas que fariam com as devidas recompensas hehe. Se estiver interessado me avisa.
> 
> Tenho interesse.. Entra em contato comigo em [hellsink@gmail.com](mailto:hellsink@gmail.com) para conversamos melhor e tirar uma dúvida, @john-titor-master

Pode me mandar mensagem no telegram. t.me/john_titor_master

**Comment by john-titor-master** [comment]
> > Eu não implementei a casa porque eu mesmo não tinha uma. No momento estou um pouco focado em outros projetos e não pretendo implementar essa funcionalidade, até porque precisaria de uma conta com uma casa para testar. Tenho alguns amigos capazes de implementar, mas que fariam com as devidas recompensas hehe. Se estiver interessado me avisa.
> 
> Tenho interesse.. Entra em contato comigo em [hellsink@gmail.com](mailto:hellsink@gmail.com) para conversamos melhor e tirar uma dúvida, @john-titor-master

Pode me enviar uma mensagem em https://t.me/john_titor_master

**Comment by GFarrel** [comment]
> > > Eu não implementei a casa porque eu mesmo não tinha uma. No momento estou um pouco focado em outros projetos e não pretendo implementar essa funcionalidade, até porque precisaria de uma conta com uma casa para testar. Tenho alguns amigos capazes de implementar, mas que fariam com as devidas recompensas hehe. Se estiver interessado me avisa.
> > 
> > 
> > Tenho interesse.. Entra em contato comigo em [hellsink@gmail.com](mailto:hellsink@gmail.com) para conversamos melhor e tirar uma dúvida, @john-titor-master
> 
> Pode me enviar uma mensagem em https://t.me/john_titor_master

@john-titor-master tried to send you a message and the user does not exist, do you have another way to communicate with you?
