### ISSUE TITLE
Adventure Mode

### ISSUE THREAD

**Issue by ghost** [john-titor-master/bombcrypto-superbot#63]
**what happens if i activate adventure mode? being that it is deprecated**

**Comment by rastogiujj12** [comment]
you get banned. 
The adventure mode is not set up to follow the cooldown limit as implemented by the game, so it uses the same hero over and over until you run out of keys.
There may be more than the above reason why it is deprecated.

**Comment by ghost** [comment]
> you get banned. The adventure mode is not set up to follow the cooldown limit as implemented by the game, so it uses the same hero over and over until you run out of keys. There may be more than the above reason why it is deprecated.

thank u
