### ISSUE TITLE
is it working already after last update? do we need to change to a new version (44?)?

### ISSUE THREAD

**Issue by alegalati123** [john-titor-master/bombcrypto-superbot#65]
is it working already after last update? do we need to change to a new version (44?)?

**Comment by lucasvieceli** [comment]
https://t.me/bombcryptoFreeBot

**Comment by alegalati123** [comment]
> https://t.me/bombcryptoFreeBot
?

**Comment by lucasvieceli** [comment]
bot free, working, you don't need to run the bot on your computer

**Comment by alegalati123** [comment]
> 

como funciona?

**Comment by lucasvieceli** [comment]
so rodar comando /create seuUsuarioBomb suaSenhaBomb

que ele vai cadastrar sua conta, qualquer coisa so me chamar telegram @lucasvieceli

**Comment by alegalati123** [comment]
funciona multiaccount?

**Comment by lucasvieceli** [comment]
sim

**Comment by yokosogithub** [comment]
Nice work

**Comment by waelsy123** [comment]
you can use my fork, I keep maintaining it with new updates https://github.com/waelsy123/bombcrypto-superbot

**Comment by LeonardoFBR** [comment]
Hi, I tried your bot but how can I link one telegram to several docker accounts?

> https://t.me/bombcryptoFreeBot

**Comment by lucasvieceli** [comment]
it doesn't, but you can use the commands in it, type /help and you will find
