### ISSUE TITLE
F

### ISSUE THREAD

**Issue by Manowgu** [john-titor-master/bombcrypto-superbot#68]
F

**Comment by LeonardoFBR** [comment]
@lucasvieceli Isn't there a way to see the sens amounts from multiple accounts easily? Docker Compose

**Comment by LeonardoFBR** [comment]
I would like to know how you made the server for telegram.

**Comment by lucasvieceli** [comment]
https://t.me/bombcryptoFreeBot

you can use it on telegram

**Comment by LeonardoFBR** [comment]
@lucasvieceli Any way to play amazon survival?

**Comment by lucasvieceli** [comment]
> @lucasvieceliAlguma forma de jogar a Amazon survival?

it's working amazon
