### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by joseeduardopd** [john-titor-master/bombcrypto-superbot#7]
Boa tarde mano, parabens pelo projeto. Teria como dar uma instrucao pra quem e leigo conseguir rodar o bot usando windows? Valeu!

**Comment by john-titor-master** [comment]
Ola @joseeduardopd.

Primeiramente você vai precisar instalar o git : https://git-scm.com/downloads

Depois, você precisa instalar o nodejs: https://nodejs.org/en/download/

Com ambos instalados, você pode ir na sua área de trabalho e clicar com o botão direito em “Git Bash”. Vai abrir um terminal.

Execute os seguintes comandos:

```bash
npm install -g yarn
git clone https://github.com/john-titor-master/bombcrypto-superbot
cd bombcrypto-superbot
yarn install
```
Com isto feito, sempre que for rodar, abre o git bash, mas agora abra-o a partir da pasta do bot que você criou na área de trabalho.

Com ele aberto, você roda o seguinte comando:

`WALLET_ID=<coloca a wallet aqui sem os sinais de menor e maior> yarn go`

Se funcionar, me avisa para fechar esse post.

**Comment by joseeduardopd** [comment]
Fiz os procedimentos aqui e tive um problema na hr de executar.
![form](https://user-images.githubusercontent.com/100960116/156855192-cc9bf5ba-18da-4b18-a5c6-9f0fee66248f.jpg)

**Comment by john-titor-master** [comment]
O erro está relacionado a formatação. Possivelmente algo do windows. Tenta rodar assim:

```sh
yarn build
WALLET_ID=<id da carteira> yarn start
```

Esse primeiro comando compila o código. O segundo roda de fato. Usando assim ele não checa formatação.

**Comment by joseeduardopd** [comment]
funcionou 100% aqui, mt obg e de novo parabéns pelo projeto, ta mt bem escrito.
