### ISSUE TITLE
Mineraland

### ISSUE THREAD

**Issue by ghost** [john-titor-master/bombcrypto-superbot#70]
Fala meu querido @lucasvieceli percebi que você fala português também.
Então, tem alguma forma de você alterar esse bot para funcionar com o game mineraland ? Ele é a mesma coisa que o bombcrypto só muda os gráficos, ate os modos e o work funcionam da mesma forma, só estou pedindo mesmo porque esse bot em node salvou meu pc hahahah

o link do game: https://play.mineraland.io/

Se precisar de uma conta para testar, estou à disposição.

**Comment by lucasvieceli** [comment]
vou da uma verificada se é simples depois me manda uma conta, @lucasvieceli  no telegram

**Comment by lucasvieceli** [comment]
verifiquei, parece ser mais facil que o bomb

mas não é mesma coisa, teria que fazer um novo bot, no momento não tenho tempo =/
