### ISSUE TITLE
Adventure mode safe?

### ISSUE THREAD

**Issue by rastogiujj12** [john-titor-master/bombcrypto-superbot#71]
Bombcrypto was banning accounts that were using the adventure mode. Is it safe now, if yes, please list what changed?
Thanks

**Comment by lucasvieceli** [comment]
from the tests I did, it's not banning anymore, but it's still not 100% guaranteed.

In the past, the bot entered adventure mode and simply entered the portal. Now he respects if the hero is available for use, kills all enemies and then enters the portal.

every 10 min he tries to play adventure mode
