### ISSUE TITLE
[Sugestão] Docker Hub

### ISSUE THREAD

**Issue by LeartPinheiro** [john-titor-master/bombcrypto-superbot#72]
Olá! meus amigos!  Esse projeto é maravilho e creio que ele ficaria ainda mais maravilhoso se fosse colocado no Docker Hub, para podermos baixar direto de la e simplesmente colocar online com arquivos env, sem necessidade de baixar e 'compilar' tudo do zero.

**Comment by lucasvieceli** [comment]
ok, mais pra frente irei colocar dockerhub

**Comment by lucasvieceli** [comment]
adiconei ao dockerhub vieceli/bombcrypto-superbot

https://github.com/john-titor-master/bombcrypto-superbot#readme
