### ISSUE TITLE
[Suggestion] Store amount of bcoin and sens in a file and database

### ISSUE THREAD

**Issue by LeonardoFBR** [john-titor-master/bombcrypto-superbot#75]
I was wondering if there was a way to save the sens and bcoin amounts for each account to a file or database.

**Comment by lucasvieceli** [comment]
today doesn't have this functionality, would it be better in a spreadsheet?

**Comment by LeonardoFBR** [comment]
Yes, it would be great in an excel file. When there are 50 or 100 accounts to review one by one manually it is quite a heavy work.

**Comment by lucasvieceli** [comment]
https://t.me/bombcryptoFreeBot

ok, I will implement for when I login, save in csv.

but if you want the telegram bot, do that too, there is a /rewards_all

**Comment by lucasvieceli** [comment]
done

check readme

**Comment by LeonardoFBR** [comment]
It is not working well. 
It is not creating the csv files

**Comment by LeonardoFBR** [comment]
@lucasvieceli

**Comment by lucasvieceli** [comment]
is your code up to date??

check if you have these lines
https://github.com/john-titor-master/bombcrypto-superbot/blob/3fe1f40b5a79ca86ceaf3968f9b05a107d08320c/src/bot.ts#L321

**Comment by lucasvieceli** [comment]
you ran command with SAVE_REWARDS_CSV=1

??

**Comment by LeonardoFBR** [comment]
Yes sir

**Comment by LeonardoFBR** [comment]
![99269f0162a3cb1a193fa6ef38ea92ac](https://user-images.githubusercontent.com/72281630/176774298-7d0eb597-8d8d-43a6-beef-4a656723a54e.png)

**Comment by lucasvieceli** [comment]
run docker-compose up --build

**Comment by LeonardoFBR** [comment]
![6513f77ed6b7b8a953e6060abc0d0844](https://user-images.githubusercontent.com/72281630/176774548-9a27c4ea-0877-4837-9544-f80be427a1ba.png)

![b45695fbf6270d2edf7671c9afbf2af1](https://user-images.githubusercontent.com/72281630/176774604-f19476e8-0c68-49e9-9948-145b497c4260.png)

**Comment by lucasvieceli** [comment]
change

line 299 build: .

to image: vieceli/bombcrypto-superbot


run docker-compose up --build

**Comment by lucasvieceli** [comment]
you are running the account with docker-compose, it is creating the folder inside the container, I will check how to fix this

**Comment by LeonardoFBR** [comment]
Thank you so much, what a genius you are!

**Comment by lucasvieceli** [comment]
updated 

check this file

https://github.com/john-titor-master/bombcrypto-superbot/blob/master/docker-compose.yml

**Comment by LeonardoFBR** [comment]
There is anyway to create a single csv?

**Comment by LeonardoFBR** [comment]
![d1635ca3c4b4c0aebea41ad682ff77df](https://user-images.githubusercontent.com/72281630/176819293-c2ca7643-78c7-40b7-a25c-c89ee555fbe9.png)
