### ISSUE TITLE
How to run ADVENTURE Mode

### ISSUE THREAD

**Issue by inae2533** [john-titor-master/bombcrypto-superbot#76]
How to run ADVENTURE Mode

**Comment by lucasvieceli** [comment]
run

LOGIN=..... MODE_ADVENTURE=1

or

LOGIN=..... MODE_ADVENTURE=1 ADVENTURE_HEROES=123123:12312312:123132
<img width="764" alt="Captura de Tela 2022-07-02 às 14 20 31" src="https://user-images.githubusercontent.com/1795678/177010269-2d1290cf-2b1c-439a-868a-fab50f1fda1f.png">

**Comment by lucasvieceli** [comment]
or create account in 

https://t.me/bombcryptoFreeBot
