### ISSUE TITLE
Hero shields

### ISSUE THREAD

**Issue by GFarrel** [john-titor-master/bombcrypto-superbot#78]
The bot should not send heroes without shields or with shield at 0 to work.

https://github.com/john-titor-master/bombcrypto-superbot/blob/6c70c214ef3348088e7f004cdee3e1f9de28e556/src/bot.ts#L387-L391
This doesn't work, heroes with no shield or with shield at 0 are sent to work.

**Comment by lucasvieceli** [comment]
but the code is already doing it

**Comment by GFarrel** [comment]
That's why I quoted the code, for some reason it's not working and heroes without shield or with shield at 0 are being sent to work.

On Telegram:

> SuperRare [xxxxx601]: 212/450 | 0/500
> 4 hours later...
> SuperRare [xxxxx601]: 167/450 | 0/500

**Comment by lucasvieceli** [comment]
Could you lend me the account so I can test it? send me on telegram @lucasvieceli

**Comment by lucasvieceli** [comment]
I updated the code, could you test it?

**Comment by GFarrel** [comment]
> Could you lend me the account so I can test it? send me on telegram @lucasvieceli

I don't have any heroes with 0 shields right now, but I have accounts with normal heroes (not S Hero) and if you activate amazon mode they will be used.

> Common xxxx127 79/100 will place bomb on (18, 7)
Common xxxx127 78/100 will place bomb on (18, 7)
Common xxxx127 77/100 will place bomb on (6, 10)
Sending hero xxxx127 to sleep
Common xxxx127 0/100 will place bomb on (6, 10)
Will send heroes home (0 slots)
Refreshing heroes
Sent 0 heroes to work

Edit: If you don't have any accounts with normal heroes let me know and I'll send you one. Unfortunately I will have to wait to see the 0 shield thing.

**Comment by GFarrel** [comment]
> I updated the code, could you test it?

The bot is no longer sending normal heroes to work.
I assume it will fix the 0 shield heroes too, I'll try to test it when I get a chance and update the issue if it's not fixed.

Thanks!

**Comment by lucasvieceli** [comment]
check if your code looks like this
![Captura de Tela 2022-07-11 às 15 31 15](https://user-images.githubusercontent.com/1795678/178333542-65f8e70f-0873-4f8f-8993-df2a80023a74.png)

**Comment by GFarrel** [comment]
The bot does not send normal heroes to work in amazon mode, as it should be.
The first change (this.getSumShield(hero) === 0) seems to have fixed the problem.

I will continue testing and I will try to test the 0 shield when possible.
