### ISSUE TITLE
No shield, no home

### ISSUE THREAD

**Issue by GFarrel** [john-titor-master/bombcrypto-superbot#80]
Do not send home heroes without shields

![image](https://user-images.githubusercontent.com/104172680/179348728-996a1598-c9e1-4bfc-a016-bc8fe5b212f8.png)

By the way, #78 100% fixed!
Can we add logger there?
Something like: ```logger.info(`Hero ${hero.id} needs shield repair`);```

**Comment by lucasvieceli** [comment]
add log

**Comment by GFarrel** [comment]
> add log

Thanks, however opened another issue because there's another problem.

Let me explain...

The bot is sending home heroes without shields (as you can see in the image, 0 shield and at home)
Those heroes will not go to work (since they do not have shields, they do not work)
Therefore you should not use the house with those heroes.

**Comment by lucasvieceli** [comment]
fixed, test please

thanks for the warnings

**Comment by GFarrel** [comment]
Fixed, thanks!
