### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by ghost** [john-titor-master/bombcrypto-superbot#81]
Colocar a linha de comando para iniciar com modo amazon + o log csv no readme, estou com dificuldade em iniciar o bot com essas configuraçoes.
Grato

**Comment by lucasvieceli** [comment]
qual comando você esta usando?

**Comment by ghost** [comment]
> qual comando você esta usando?

estou seguindo o que esta no readme mas diz que é comando invalido, digo os parametros antes do yarn go

**Comment by lucasvieceli** [comment]
manda print do comando e do erro

**Comment by ghost** [comment]
> manda print do comando e do erro

https://prnt.sc/jnw29tzeqsS8

**Comment by lucasvieceli** [comment]
MODE_AMAZON=1
SAVE_REWARDS_CSV=1

**Comment by ghost** [comment]
> MODE_AMAZON=1 SAVE_REWARDS_CSV=1

perfeito man, funcionou valeuu
