### ISSUE TITLE
lista de atualizações

### ISSUE THREAD

**Issue by veenx67** [john-titor-master/bombcrypto-superbot#83]
Uma lista de coisas não tão uteis, mas que ajudariam muito

- [ ] Adicionar comandos novos. /start_account /stop /shield

- [ ] Adicionar mensagem automatica com os comandos no telegram, quando o bot inicia
```
Source :  https://github.com/john-titor-master/bombcrypto-superbot 
Faça uma doação para ajudar o desenvolvimento do bot :) 
0x5AAe945cD56eE21ea3f63b6772fcD5e71713C2ee

/start_account -- Iniciar o Bot

/stop -- Pausar o Bot

/stats -- Listar informações da conta

/shield -- Listar Durabilidade do Shield

/rewards -- Mostrar Recompensas

/exit -- Desligar o Bot
```

- [ ] Só exibir as informações da rede selecionada no /rewards
- [ ] Só exibir "POLYGON-BCoin: e POLYGON-Bomberman: " e renomear para BOMB e JAULA, o resto é irrelevante para o bot

```
Rewards:
POLYGON-BCoin: 69.22
POLYGON-Bomberman: 0
POLYGON-Key: 0
POLYGON-BCoin Deposited: 0
POLYGON-Senspark: 0
POLYGON-Unknown: 0
POLYGON-WOFM: 0
POLYGON-BOSS TICKET: 0
POLYGON-PVP TICKET: 0
BSC-BCoin: 10.03
BSC-Bomberman: 0
BSC-Key: 0
BSC-Senspark: 122.42
BSC-MSPc: -0.00
BSC-WOFM: 8.10
```

**Comment by lucasvieceli** [comment]
não será possivel ter start nem stop

**Comment by veenx67** [comment]
entendi, mas o resto é possivel ? :D

**Comment by lucasvieceli** [comment]
adicionado as funcionalidades
