### ISSUE TITLE
Erro apos algumas horas rodando

### ISSUE THREAD

**Issue by joseeduardopd** [john-titor-master/bombcrypto-superbot#9]
Boa tarde mano, percebi que apos algumas horas ele para e da esse erro do print. Tem alguma sugestão do que pode ser?
![term](https://user-images.githubusercontent.com/100960116/157093036-bcc46254-4f29-4826-8978-d7328345de44.png)

**Comment by dilneiss** [comment]
isso também acontece comigo

**Comment by odilklein** [comment]
Estou recebendo esse aqui, ultimamente.

![Screenshot_3](https://user-images.githubusercontent.com/99180711/157748014-2d4134b1-ab32-4497-80dd-c05a7759ab1c.png)

**Comment by john-titor-master** [comment]
Dá uma olhada na última seção do README. Atualizei agora ;)
